from typing import Optional
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import base64
import os
import re
import shutil
from pathlib import Path

import requests

try:
    from PIL import Image
    import pytesseract
except Exception:
    Image = None
    pytesseract = None

ARK_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3/images/generations"
ARK_IMAGE_MODELS = [
    "doubao-seedream-5-0-260128",
    "doubao-seedream-4-5-251128",
    "doubao-seedream-4-0-250828",
]
WATERMARK_HINTS = ["AI生成", "AIGC", "AI GENERATED", "GENERATED BY AI", "DOUBAO", "SEEDREAM"]
TEXT_PATTERN = re.compile(r"[A-Za-z\u4e00-\u9fff]")

DEFAULT_STYLE_SUFFIX = (
    "。采用明亮温馨的彩色卡通插画风格，色彩丰富饱满、柔和渐变、清新活泼，适合个人医生网站博客封面，"
    "画面健康积极、温暖安心，扁平化设计感，背景使用淡蓝色或淡绿色等清新色调。"
    "绝对不要出现任何文字、字母、数字、中文、英文、胸牌字样、标签、包装文字、屏幕文字、logo、水印、签名。"
    "绝对不要出现人体器官，不要出现器官放在餐盘、碗、托盘、桌面上的画面，不要出现内脏、血腥、手术特写、夸张疼痛表情。"
    "画面只表达日常恢复、门诊沟通、健康饮食、轻松生活方式等安全场景。"
)


def detect_unwanted_text(img_path: Path) -> bool:
    if not Image or not pytesseract:
        return False
    if not shutil.which("tesseract"):
        return False
    try:
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        rois = [img, img.crop((0, int(h * 0.70), w, h)), img.crop((0, 0, w, int(h * 0.25)))]
        merged = "\n".join(pytesseract.image_to_string(roi, lang="chi_sim+eng") for roi in rois)
        merged_upper = merged.upper()
        if any(k in merged_upper for k in WATERMARK_HINTS):
            return True
        return bool(TEXT_PATTERN.search(merged))
    except Exception:
        return False


def build_prompt(base_prompt: str) -> str:
    return base_prompt.strip() + DEFAULT_STYLE_SUFFIX


def generate_cover_image(*, slug: str, images_dir: Path, fallback_path: str, base_prompt: str, api_key: Optional[str] = None) -> str:
    key = (api_key or os.getenv("ARK_API_KEY") or "").strip()
    if not key:
        print("[WARN] ARK_API_KEY not set, using fallback image.")
        return fallback_path

    prompt = build_prompt(base_prompt)

    for model_name in ARK_IMAGE_MODELS:
        for attempt in range(1, 3):
            try:
                payload = {
                    "model": model_name,
                    "prompt": prompt,
                    "size": "2K",
                    "response_format": "url",
                    "watermark": False,
                    "stream": False,
                }
                resp = requests.post(
                    ARK_BASE_URL,
                    headers={
                        "Authorization": f"Bearer {key}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                    timeout=180,
                )
                resp.raise_for_status()
                data = resp.json().get("data", [])
                if not data:
                    raise RuntimeError("No image data from Ark")

                if data[0].get("url"):
                    img_resp = requests.get(data[0]["url"], timeout=120)
                    img_resp.raise_for_status()
                    img_bytes = img_resp.content
                elif data[0].get("b64_json"):
                    img_bytes = base64.b64decode(data[0]["b64_json"])
                else:
                    raise RuntimeError("No image URL/base64 from Ark")

                img_filename = f"blog-{slug[:60]}.png"
                img_path = images_dir / img_filename
                img_path.write_bytes(img_bytes)

                if detect_unwanted_text(img_path):
                    print(f"[WARN] Text/watermark detected ({model_name}, attempt {attempt}), retrying...")
                    try:
                        img_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    continue

                print(f"[OK] Ark image saved: {img_filename} via {model_name}")
                return f"/images/blog/{img_filename}"
            except Exception as ex:
                print(f"[WARN] Ark image failed ({model_name}, attempt {attempt}): {ex}")
                continue

    return fallback_path
