from typing import Optional
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import base64
import hashlib
import os
import re
import shutil
from pathlib import Path

import requests

try:
    from PIL import Image
    import pytesseract
except Exception:
    Image = None
    pytesseract = None

ARK_BASE_URL = "https://ark.cn-beijing.volces.com/api/v3/images/generations"
ARK_IMAGE_MODELS = [
    "doubao-seedream-5-0-260128",
    "doubao-seedream-4-5-251128",
    "doubao-seedream-4-0-250828",
]
WATERMARK_HINTS = ["AI生成", "AIGC", "AI GENERATED", "GENERATED BY AI", "DOUBAO", "SEEDREAM"]
TEXT_PATTERN = re.compile(r"[A-Za-z\u4e00-\u9fff]")

STYLE_VARIANTS = [
    "采用晨间门诊或日光室内氛围，点缀青绿色、暖金色与米白色，层次丰富，具有轻微景深。",
    "采用清爽厨房或餐桌场景，加入蔬果、谷物、陶瓷器皿和自然木纹，色彩明快但不过度饱和。",
    "采用户外散步或恢复期生活方式场景，加入天空蓝、叶绿色与柔和阳光，氛围轻松有呼吸感。",
    "采用医生与患者面对面沟通场景，加入资料讲解与手势交流，但不要出现可读文字，色彩专业温暖。",
    "采用家庭恢复与清淡饮食准备场景，加入南瓜橙、鼠尾草绿和奶油白，画面温柔有生活感。",
]

DEFAULT_STYLE_SUFFIX = (
    "统一采用高质量彩色医学插画与生活方式 editorial 风格，温暖自然、专业可信、适合个人医生网站博客封面。"
    "明确使用彩色，不要黑白、灰度、单色、铅笔稿、纯线稿效果。"
    "构图简洁高级，光线柔和，保留一定背景层次和真实生活细节。"
    "绝对不要出现任何文字、字母、数字、中文、英文、胸牌字样、标签、包装文字、屏幕文字、logo、水印、签名。"
    "绝对不要出现人体器官，不要出现器官放在餐盘、碗、托盘、桌面上的画面，不要出现内脏、血腥、手术特写、夸张疼痛表情。"
    "画面只表达日常恢复、门诊沟通、健康饮食、轻松生活方式等安全场景。"
)


def detect_unwanted_text(img_path: Path) -> bool:
    if not Image or not pytesseract:
        return False
    if not shutil.which("tesseract"):
        return False
    try:
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        rois = [img, img.crop((0, int(h * 0.70), w, h)), img.crop((0, 0, w, int(h * 0.25)))]
        merged = "\n".join(pytesseract.image_to_string(roi, lang="chi_sim+eng") for roi in rois)
        merged_upper = merged.upper()
        if any(k in merged_upper for k in WATERMARK_HINTS):
            return True
        return bool(TEXT_PATTERN.search(merged))
    except Exception:
        return False


def _pick_style_variant(variant_hint: str) -> str:
    seed = (variant_hint or "askdrliu-cover").encode("utf-8")
    index = int(hashlib.sha256(seed).hexdigest(), 16) % len(STYLE_VARIANTS)
    return STYLE_VARIANTS[index]


def build_prompt(base_prompt: str, variant_hint: str = "") -> str:
    prompt = base_prompt.strip().rstrip("。")
    style_variant = _pick_style_variant(variant_hint or prompt)
    return f"{prompt}。{style_variant}{DEFAULT_STYLE_SUFFIX}"


def generate_cover_image(*, slug: str, images_dir: Path, fallback_path: str, base_prompt: str, api_key: Optional[str] = None) -> str:
    key = (api_key or os.getenv("ARK_API_KEY") or "").strip()
    if not key:
        print("[WARN] ARK_API_KEY not set, using fallback image.")
        return fallback_path

    prompt = build_prompt(base_prompt, slug)

    for model_name in ARK_IMAGE_MODELS:
        for attempt in range(1, 3):
            try:
                payload = {
                    "model": model_name,
                    "prompt": prompt,
                    "size": "2K",
                    "response_format": "url",
                    "watermark": False,
                    "stream": False,
                }
                resp = requests.post(
                    ARK_BASE_URL,
                    headers={
                        "Authorization": f"Bearer {key}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                    timeout=180,
                )
                resp.raise_for_status()
                data = resp.json().get("data", [])
                if not data:
                    raise RuntimeError("No image data from Ark")

                if data[0].get("url"):
                    img_resp = requests.get(data[0]["url"], timeout=120)
                    img_resp.raise_for_status()
                    img_bytes = img_resp.content
                elif data[0].get("b64_json"):
                    img_bytes = base64.b64decode(data[0]["b64_json"])
                else:
                    raise RuntimeError("No image URL/base64 from Ark")

                img_filename = f"blog-{slug[:60]}.png"
                img_path = images_dir / img_filename
                img_path.write_bytes(img_bytes)

                if detect_unwanted_text(img_path):
                    print(f"[WARN] Text/watermark detected ({model_name}, attempt {attempt}), retrying...")
                    try:
                        img_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    continue

                print(f"[OK] Ark image saved: {img_filename} via {model_name}")
                return f"/images/blog/{img_filename}"
            except Exception as ex:
                print(f"[WARN] Ark image failed ({model_name}, attempt {attempt}): {ex}")
                continue

    return fallback_path
