#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Medical Blog Auto-Generator for AskDrLiu / cursor-site
-------------------------------------------------------
- Fetches latest medical news (gallbladder, longevity, diet)
- Generates bilingual (zh/en) blog post via Zhipu GLM-4-Plus API
- Fetches a relevant cover image from Pexels
- Saves markdown to public/blog-posts/
- Auto-registers the post in src/data/blog-posts.ts

Run daily via GitHub Actions or manually.
"""

import os
import re
import json
import time
import random
import string
import shutil
import requests
import feedparser
from datetime import datetime, timezone
from pathlib import Path

from zhipuai import ZhipuAI

# ─────────────────────────── Config ───────────────────────────
REPO_ROOT = Path(__file__).resolve().parents[1]
BLOG_MD_DIR = REPO_ROOT / "public" / "blog-posts"
BLOG_INDEX_FILE = REPO_ROOT / "src" / "data" / "blog-posts.ts"
IMAGES_DIR = REPO_ROOT / "public" / "images" / "blog"

BLOG_MD_DIR.mkdir(parents=True, exist_ok=True)
IMAGES_DIR.mkdir(parents=True, exist_ok=True)

ZHIPU_API_KEY = os.getenv("ZHIPU_API_KEY", "").strip()
SILICONFLOW_API_KEY = os.getenv("SILICONFLOW_API_KEY", "").strip()

MODEL = "glm-4-plus"              # 智谱清言文本模型
# 统一切换到 SiliconFlow（避免 Seedream 平台水印）
SILICONFLOW_IMAGE_MODELS = [
    "black-forest-labs/FLUX.1-dev",
    "black-forest-labs/FLUX.1-schnell",
]
SILICONFLOW_BASE_URL = "https://api.siliconflow.cn/v1/images/generations"
WATERMARK_HINTS = ["AI生成", "AIGC", "AI GENERATED", "GENERATED BY AI", "DOUBAO", "SEEDREAM"]
TEXT_PATTERN = re.compile(r"[A-Za-z\u4e00-\u9fff]")

# RSS sources: strict hepatobiliary focus
FEED_URLS = [
    "https://www.sciencedaily.com/rss/health_medicine/gallbladder_disease.xml",
    "https://www.sciencedaily.com/rss/health_medicine/liver_disease.xml",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=gallbladder+stone+cholecystitis&format=rss&limit=30",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=cholecystectomy+postoperative+nutrition&format=rss&limit=30",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=gallbladder+preservation+cholelithiasis&format=rss&limit=25",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=liver+health+longevity&format=rss&limit=20",
]

# Image search keywords mapped to topics
IMAGE_KEYWORDS = {
    "gallbladder": ["healthy food", "digestive health", "nutrition", "medical"],
    "liver": ["liver health", "healthy lifestyle", "medical research"],
    "longevity": ["longevity", "healthy aging", "exercise lifestyle"],
    "nutrition": ["healthy food", "vegetables", "mediterranean diet"],
    "default": ["healthcare", "medical", "healthy lifestyle"],
}

FOCUS_KEYWORDS = [
    "gallbladder", "gallstone", "cholelithiasis", "cholecystitis", "cholecystectomy",
    "post-cholecystectomy", "gallbladder preservation", "biliary", "bile", "pocs",
    "diet after cholecystectomy", "gallbladder inflammation",
]

BLOCK_KEYWORDS = [
    "organ transplant", "transplantation", "kidney transplant", "heart transplant",
    "lung transplant", "donor", "allograft", "immunosuppression",
]


# ─────────────────────────── RSS Fetch ───────────────────────────
def fetch_entries(feed_url: str, timeout=20):
    try:
        d = feedparser.parse(feed_url, request_headers={"User-Agent": "AskDrLiu-Bot/1.0"})
        entries = []
        for e in d.entries[:30]:
            title = (e.get("title") or "").strip()
            link = (e.get("link") or "").strip()
            summary = re.sub(r"\s+", " ", (e.get("summary") or e.get("description") or "").strip())
            if title and link:
                entries.append({"title": title, "link": link, "summary": summary[:800]})
        return entries
    except Exception as ex:
        print(f"[WARN] Feed failed: {feed_url} → {ex}")
        return []


def pick_topic(all_entries):
    if not all_entries:
        raise RuntimeError("No RSS entries. Check feeds or network.")

    focus = [k.lower() for k in FOCUS_KEYWORDS]
    block = [k.lower() for k in BLOCK_KEYWORDS]

    # 仅保留肝胆目标话题，并剔除器官移植类
    filtered = []
    for e in all_entries:
        t = (e["title"] + " " + e["summary"]).lower()
        if any(k in t for k in block):
            continue
        if any(k in t for k in focus):
            filtered.append(e)

    if filtered:
        return filtered[0]

    raise RuntimeError("No eligible hepatobiliary topics found (after transplant exclusion).")


def detect_topic_type(title: str, summary: str) -> str:
    text = (title + " " + summary).lower()
    if any(k in text for k in ["gallbladder", "gallstone", "bile", "cholecyst", "ercp", "pocs"]):
        return "gallbladder"
    if any(k in text for k in ["liver", "hepatic", "fatty liver"]):
        return "liver"
    if any(k in text for k in ["longevity", "aging", "lifespan", "centenar"]):
        return "longevity"
    if any(k in text for k in ["nutrition", "diet", "food", "vitamin", "mineral"]):
        return "nutrition"
    return "default"


# ─────────────────────────── Claude Generation ───────────────────────────
SYSTEM_PROMPT = """You are a senior physician (hepatobiliary surgery specialist) writing bilingual medical education content.
Rules:
- Educational only — not diagnosis or personal medical advice.
- No fear-based language, no absolute treatment claims.
- Clear structure, short paragraphs, practical guidance.
- When evidence is uncertain, explicitly say so.
- Include a brief "When to see a doctor" section.
- Output MUST be valid JSON only (no markdown fences).

JSON structure:
{
  "title": "中文标题 (max 30 chars)",
  "titleEn": "English title (max 60 chars)",
  "excerpt": "中文摘要 (80-120 chars, no newlines)",
  "excerptEn": "English excerpt (100-160 chars, no newlines)",
  "category": "中文分类 (one of: 保胆 | 胆囊炎 | 胆囊结石 | 胆囊切除术后营养 | 胆囊与长寿 | 肝脏健康)",
  "categoryEn": "English category (one of: Gallbladder Preservation | Cholecystitis | Gallstones | Post-Cholecystectomy Nutrition | Gallbladder & Longevity | Liver Health)",
  "tags": ["tag1", "tag2", "tag3"],
  "markdownZh": "中文正文 markdown (1200-1800字，含“参考文献”段)",
  "markdownEn": "English body markdown (800-1200 words, include 'References')"
}"""

USER_PROMPT = """Generate a bilingual medical blog post based on this news cue.

Headline: {headline}
Source URL: {url}
Summary: {summary}

Key focus areas: {focus}

Chinese article requirements:
- Topic must stay strictly within hepatobiliary scope, prioritizing: gallbladder preservation, cholecystitis, gallstones, post-cholecystectomy nutrition, gallbladder-related longevity, liver health
- Length must be 1200-1800 Chinese characters (do not write short posts)
- Hook (1-2 lines that make readers curious)
- What this research means for patients
- 3-5 practical takeaways (bullet points)
- When to seek medical care (bullets)
- Add section `## 参考文献` with 3-6 real sources, each as markdown list item with title/journal/year/URL
- One-line disclaimer

English article requirements:
- Same structure but natural English tone
- Length 800-1200 words
- Add section `## References` with 3-6 real sources

Return valid JSON only."""


def _extract_reference_urls(markdown_text: str) -> list[str]:
    return re.findall(r"https?://[^\s)]+", markdown_text)


def _url_reachable(u: str) -> bool:
    try:
        r = requests.head(u, timeout=12, allow_redirects=True)
        if r.status_code < 400:
            return True
    except Exception:
        pass
    try:
        r = requests.get(u, timeout=15, allow_redirects=True)
        return r.status_code < 400
    except Exception:
        return False


def _validate_references(data: dict):
    zh = data.get("markdownZh", "")
    en = data.get("markdownEn", "")

    if "参考文献" not in zh:
        raise ValueError("Missing `参考文献` section in Chinese article")
    if "References" not in en:
        raise ValueError("Missing `References` section in English article")

    urls = list(dict.fromkeys(_extract_reference_urls(zh) + _extract_reference_urls(en)))
    if len(urls) < 3:
        raise ValueError(f"Not enough reference URLs (found {len(urls)}, require >=3)")

    unreachable = [u for u in urls[:8] if not _url_reachable(u)]
    if unreachable:
        raise ValueError("Unreachable reference URLs: " + ", ".join(unreachable[:3]))


def generate_post(headline: str, url: str, summary: str) -> dict:
    if not ZHIPU_API_KEY:
        raise RuntimeError("Missing ZHIPU_API_KEY")
    client = ZhipuAI(api_key=ZHIPU_API_KEY)

    prompt = USER_PROMPT.format(
        headline=headline,
        url=url,
        summary=summary[:600],
        focus=", ".join(FOCUS_KEYWORDS[:8]),
    )

    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0.4,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt},
        ],
    )

    text = resp.choices[0].message.content.strip()

    # Parse JSON
    try:
        data = json.loads(text)
    except Exception:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            raise ValueError(f"Model did not return JSON:\n{text[:300]}")
        data = json.loads(m.group(0))

    required = ["title", "titleEn", "excerpt", "excerptEn", "category", "categoryEn", "tags", "markdownZh", "markdownEn"]
    for k in required:
        if k not in data:
            raise ValueError(f"Missing key: {k}")

    _validate_references(data)
    return data


# ─────────────────────────── AIGC Image Generation (火山方舟) ───────────────────────────

try:
    from PIL import Image
    import pytesseract
except Exception:
    Image = None
    pytesseract = None


def detect_unwanted_text(img_path: Path) -> bool:
    """OCR 检测图片中任意可识别文字（中英文/数字字母/水印词）。命中则判失败。"""
    if not Image or not pytesseract:
        return False
    if not shutil.which("tesseract"):
        return False
    try:
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        rois = [
            img,  # 全图
            img.crop((0, int(h * 0.72), w, h)),  # 底部常见水印区
        ]
        texts = []
        for roi in rois:
            raw = pytesseract.image_to_string(roi, lang="chi_sim+eng")
            texts.append(raw)
        merged = "\n".join(texts)
        merged_upper = merged.upper()

        if any(k in merged_upper for k in WATERMARK_HINTS):
            return True
        if TEXT_PATTERN.search(merged):
            return True
        return False
    except Exception:
        return False


# 各话题的中文生图提示词
def load_gallbladder_prompts():
    prompts_path = Path(__file__).parent.parent.parent.parent / ".prompts/gallery/gallbladder-health-cover-prompts-v1.md"
    if prompts_path.exists():
        text = prompts_path.read_text(encoding="utf-8")
        blocks = re.findall(r"## 提示词 (\d+) – (.+?)\n```json\n(\{.+?\})\n```", text, re.DOTALL)
        if blocks:
            return blocks  # list of (num, title, json)
    return None


GALLBLADDER_PROMPTS_REGISTRY = load_gallbladder_prompts()

IMAGE_PROMPTS = {
    "gallbladder": (
        "Modern medical education scene for gallbladder health; clean calm reassuring tone, "
        "soft natural lighting with subtle volumetric effects; "
        "no blood, no gore, no wounds, no frightening scene, no pain-expression close-up; "
        "keep hyper photorealistic, professional, trustworthy"
    ),
    "liver": (
        "Realistic modern medical illustration of liver and hepatobiliary health, clinical style, "
        "clean composition, bright natural lighting"
    ),
    "longevity": (
        "Health longevity scene explicitly linked to hepatobiliary metabolic health, "
        "modern preventive medicine style, realistic photography-like rendering"
    ),
    "nutrition": (
        "Post-cholecystectomy nutrition medical illustration, low-fat recovery meal and patient education context, "
        "modern clinical health style, realistic rendering"
    ),
    "default": (
        "Modern hepatobiliary medical education illustration, realistic, clean, professional"
    ),
}

def generate_siliconflow_image(topic_type: str, slug: str) -> str:
    """使用 SiliconFlow 生成配图，保存到本地并返回相对路径。"""
    fallback_map = {
        "gallbladder": "/images/gallstone-prevention.jpg",
        "liver": "/images/liver-health.jpg",
        "longevity": "/images/dietary-guidance.jpg",
        "nutrition": "/images/dietary-guidance.jpg",
        "default": "/images/recovery-guide.jpg",
    }

    if not SILICONFLOW_API_KEY:
        print("[WARN] SILICONFLOW_API_KEY not set, using fallback image.")
        return fallback_map.get(topic_type, "/images/pocs-surgery.jpg")

    prompt = IMAGE_PROMPTS.get(topic_type, IMAGE_PROMPTS["default"]) + "; strict constraints: no text, no letters, no Chinese characters, no symbols, no logo, no watermark, no signature, no calligraphy, no ancient style, no traditional Chinese painting, no fantasy scene, no moon palace aesthetics, no blood, no gore, no wounds, no frightening scene, no pain-expression close-up, no graphic surgery close-up; keep calm, clean, reassuring medical education tone."

    for model_name in SILICONFLOW_IMAGE_MODELS:
        for attempt in range(1, 3):
            try:
                payload = {
                    "model": model_name,
                    "prompt": prompt,
                    "image_size": "1280x720",  # 16:9 横版，适合博客封面
                }
                resp = requests.post(
                    SILICONFLOW_BASE_URL,
                    headers={
                        "Authorization": f"Bearer {SILICONFLOW_API_KEY}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                    timeout=120,
                )
                resp.raise_for_status()
                data = resp.json().get("data", [])
                if not data:
                    raise RuntimeError("No image data from SiliconFlow")

                if data[0].get("url"):
                    img_resp = requests.get(data[0]["url"], timeout=60)
                    img_resp.raise_for_status()
                    img_bytes = img_resp.content
                elif data[0].get("b64_json"):
                    import base64
                    img_bytes = base64.b64decode(data[0]["b64_json"])
                else:
                    raise RuntimeError("No image URL/base64 from SiliconFlow")

                img_filename = f"blog-{slug[:40]}.jpg"
                img_path = IMAGES_DIR / img_filename
                img_path.write_bytes(img_bytes)

                if detect_unwanted_text(img_path):
                    print(f"[WARN] Text/watermark detected ({model_name}, attempt {attempt}), retrying...")
                    try:
                        img_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    continue

                print(f"[OK] AIGC image saved: {img_filename} via {model_name}")
                return f"/images/blog/{img_filename}"
            except Exception as ex:
                print(f"[WARN] SiliconFlow image failed ({model_name}, attempt {attempt}): {ex}")
                continue

    return fallback_map.get(topic_type, "/images/pocs-surgery.jpg")


# ─────────────────────────── Save Markdown ───────────────────────────
def save_markdown(slug: str, data: dict, image_url: str, source_url: str):
    today = datetime.now().strftime("%Y-%m-%d")

    # Chinese markdown file
    zh_path = BLOG_MD_DIR / f"{slug}.md"
    zh_header = f"""---
title: {data['title']}
date: {today}
category: {data['category']}
image: {image_url}
source: {source_url}
---

"""
    zh_path.write_text(zh_header + data["markdownZh"].strip() + "\n", encoding="utf-8")

    # English markdown file
    en_path = BLOG_MD_DIR / f"{slug}-en.md"
    en_header = f"""---
title: {data['titleEn']}
date: {today}
category: {data['categoryEn']}
image: {image_url}
source: {source_url}
---

"""
    en_path.write_text(en_header + data["markdownEn"].strip() + "\n", encoding="utf-8")

    print(f"[OK] Saved: {zh_path.name} + {en_path.name}")
    return str(zh_path), str(en_path)


# ─────────────────────────── Update blog-posts.ts ───────────────────────────
def update_blog_index(slug: str, data: dict, image_url: str):
    """Insert new post entry into src/data/blog-posts.ts"""
    today = datetime.now().strftime("%Y-%m-%d")

    esc = lambda s: (s or "").replace("'", "\\'")
    title = esc(data.get("title", ""))
    title_en = esc(data.get("titleEn", ""))
    excerpt = esc(data.get("excerpt", ""))
    excerpt_en = esc(data.get("excerptEn", ""))
    category = esc(data.get("category", ""))
    category_en = esc(data.get("categoryEn", ""))

    new_entry = f"""  {{
    id: '{slug}',
    title: '{title}',
    titleEn: '{title_en}',
    excerpt: '{excerpt}',
    excerptEn: '{excerpt_en}',
    date: '{today}',
    category: '{category}',
    categoryEn: '{category_en}',
    imageUrl: '{image_url}',
    author: 'AskDrLiu.com'
  }},"""

    content = BLOG_INDEX_FILE.read_text(encoding="utf-8")

    # Insert after "export const blogPosts: BlogPost[] = ["
    marker = "export const blogPosts: BlogPost[] = ["
    if marker not in content:
        print("[WARN] Could not find blogPosts array marker. Skipping auto-insert.")
        print(f"[INFO] Manually add this entry:\n{new_entry}")
        return

    insert_pos = content.index(marker) + len(marker)
    # Skip any whitespace/newline after marker
    new_content = content[:insert_pos] + "\n" + new_entry + content[insert_pos:]
    BLOG_INDEX_FILE.write_text(new_content, encoding="utf-8")
    print(f"[OK] Registered in blog-posts.ts: {slug}")


# ─────────────────────────── Main ───────────────────────────
def make_slug(title: str) -> str:
    """Generate a URL-friendly slug from Chinese or English title."""
    # Remove non-alphanumeric (keep spaces)
    clean = re.sub(r"[^\w\s-]", "", title, flags=re.UNICODE)
    clean = re.sub(r"\s+", "-", clean.strip()).lower()
    # Limit length and add random suffix
    clean = clean[:40]
    suffix = "".join(random.choices(string.ascii_lowercase + string.digits, k=6))
    today = datetime.now().strftime("%Y%m%d")
    return f"{today}-{clean}-{suffix}" if clean else f"{today}-post-{suffix}"


def main():
    print("=== AskDrLiu Medical Blog Auto-Generator ===")

    # 1. Fetch RSS feeds
    all_entries = []
    for url in FEED_URLS:
        entries = fetch_entries(url)
        all_entries.extend(entries)
        if entries:
            print(f"[OK] {url} → {len(entries)} entries")

    if not all_entries:
        print("[ERROR] No RSS entries fetched. Exiting.")
        return

    # 2. Pick topic
    topic = pick_topic(all_entries)
    print(f"\n[TOPIC] {topic['title']}\n  → {topic['link']}")

    # 3. Detect topic type for image matching
    topic_type = detect_topic_type(topic["title"], topic["summary"])

    # 4. Generate bilingual post
    print("[GEN] Calling Claude API...")
    data = generate_post(topic["title"], topic["link"], topic["summary"])
    print(f"[OK] Generated: {data['title']} / {data['titleEn']}")

    # 5. AIGC 生成封面图
    slug = make_slug(data["title"])
    print("[IMG] Generating AIGC cover image via SiliconFlow...")
    image_url = generate_siliconflow_image(topic_type, slug)
    print(f"[OK] Image: {image_url}")

    # 6. Save markdown files
    save_markdown(slug, data, image_url, topic["link"])

    # 7. Update blog-posts.ts
    update_blog_index(slug, data, image_url)

    # 8. Update sitemap.xml
    update_sitemap()

    print(f"\n✅ Done! Slug: {slug}")
    print("   Next: commit & push → Vercel will auto-deploy.")


if __name__ == "__main__":
    main()
