#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Weekly Blog Pipeline for AskDrLiu / cursor-site
------------------------------------------------
运行时机：每周日 08:00 (北京时间)
功能：
  1. 从 PubMed RSS + Reddit + 搜索 抓取话题
  2. 用 GLM-5 筛选 7 个最优话题
  3. 批量生成 7 篇草稿（正文 + Seedream 5.0 配图）
  4. 写入发布队列 scripts/queue.json
  5. 通过 Telegram 推送话题清单供用户审核
"""

import os, re, json, random, string, requests, feedparser, warnings, hashlib, shutil
from datetime import datetime, timedelta
from pathlib import Path

warnings.filterwarnings("ignore")
from zhipuai import ZhipuAI

try:
    from PIL import Image
    import pytesseract
except Exception:
    Image = None
    pytesseract = None

# ─── 路径 ───────────────────────────────────────────────
REPO_ROOT   = Path(__file__).resolve().parents[1]
DRAFTS_DIR  = REPO_ROOT / "public" / "blog-posts" / "drafts"
IMAGES_DIR  = REPO_ROOT / "public" / "images" / "blog"
QUEUE_FILE  = REPO_ROOT / "scripts" / "queue.json"
INDEX_FILE  = REPO_ROOT / "src" / "data" / "blog-posts.ts"

DRAFTS_DIR.mkdir(parents=True, exist_ok=True)
IMAGES_DIR.mkdir(parents=True, exist_ok=True)

# ─── API Keys ───────────────────────────────────────────
ZHIPU_KEY   = os.getenv("ZHIPU_API_KEY", "")
SILICONFLOW_KEY = os.getenv("SILICONFLOW_API_KEY", "")
TG_TOKEN    = os.getenv("TELEGRAM_BOT_TOKEN", "")
TG_CHAT_ID  = os.getenv("TELEGRAM_CHAT_ID", "1094807201")

# ─── 模型 ────────────────────────────────────────────────
GLM_MODEL   = "glm-5"
GLM_FALLBACK= "glm-4-plus"
# 统一切换到 SiliconFlow（避免 Seedream 平台水印）
SILICONFLOW_MODELS = ["black-forest-labs/FLUX.1-schnell"]
SILICONFLOW_URL = "https://api.siliconflow.cn/v1/images/generations"
WATERMARK_HINTS = ["AI生成", "AIGC", "AI GENERATED", "GENERATED BY AI", "DOUBAO", "SEEDREAM"]
TEXT_PATTERN = re.compile(r"[A-Za-z\u4e00-\u9fff]")

# ─── RSS 来源 ─────────────────────────────────────────────
FEED_URLS = [
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=gallbladder+stone+cholecystitis&format=rss&limit=30",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=cholecystectomy+postoperative+nutrition&format=rss&limit=30",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=gallbladder+preservation+cholelithiasis&format=rss&limit=25",
    "https://pubmed.ncbi.nlm.nih.gov/rss/search/?term=liver+health+longevity&format=rss&limit=20",
    "https://www.sciencedaily.com/rss/health_medicine/gallbladder_disease.xml",
    "https://www.sciencedaily.com/rss/health_medicine/liver_disease.xml",
]

REDDIT_SUBS = ["gallbladders", "liver"]

FOCUS_TERMS = [
    "gallbladder", "gallstone", "cholelithiasis", "cholecystitis", "cholecystectomy",
    "post-cholecystectomy", "bile", "biliary", "liver", "hepatic", "pocs",
]

IMAGE_PROMPTS = {
    "胆囊结石": "医学科普插图，胆囊结石与胆道系统主题，真实解剖感，专业干净医疗场景，无文字，高清",
    "胆囊炎": "医学科普插图，胆囊炎症与右上腹不适主题，临床风格，蓝绿色调，无文字，高清",
    "保胆": "医学科普插图，保胆理念与微创胆道镜操作场景，专业明亮，无文字，高清",
    "胆囊切除术后营养": "术后饮食康复主题，低脂健康餐盘与康复场景，医学科普风格，无文字，高清",
    "胆囊与长寿": "胆囊代谢健康与健康老龄化主题，积极生活方式，医学感，无文字，高清",
    "肝脏健康": "医学健康主题，肝脏保健，绿色自然色调，温暖阳光，无文字，高清",
    "default":  "肝胆健康科普插图，医学专业风，干净简洁，无文字，高清",
}


# ─── 1. 抓取话题 ──────────────────────────────────────────
def is_focus_entry(title: str, summary: str) -> bool:
    text = f"{title} {summary}".lower()
    return any(k in text for k in FOCUS_TERMS)


def fetch_rss_entries():
    entries = []
    for url in FEED_URLS:
        try:
            d = feedparser.parse(url, request_headers={"User-Agent": "AskDrLiu/1.0"})
            for e in d.entries[:15]:
                title   = (e.get("title") or "").strip()
                link    = (e.get("link") or "").strip()
                summary = re.sub(r"\s+", " ", (e.get("summary") or "").strip())[:500]
                if title and link and is_focus_entry(title, summary):
                    entries.append({"title": title, "link": link, "summary": summary, "source": "pubmed"})
        except Exception as ex:
            print(f"[WARN] RSS {url}: {ex}")
    print(f"[RSS] {len(entries)} entries")
    return entries


def fetch_reddit_entries():
    entries = []
    for sub in REDDIT_SUBS:
        try:
            url  = f"https://www.reddit.com/r/{sub}/hot.json?limit=10"
            resp = requests.get(url, headers={"User-Agent": "AskDrLiu/1.0"}, timeout=15)
            posts = resp.json().get("data", {}).get("children", [])
            for p in posts:
                d = p.get("data", {})
                title = d.get("title", "").strip()
                score = d.get("score", 0)
                if title and score > 50 and is_focus_entry(title, d.get("selftext", "")):
                    entries.append({
                        "title":   title,
                        "link":    f"https://reddit.com{d.get('permalink','')}",
                        "summary": d.get("selftext", "")[:300],
                        "source":  f"reddit/r/{sub}",
                        "score":   score,
                    })
        except Exception as ex:
            print(f"[WARN] Reddit r/{sub}: {ex}")
    print(f"[Reddit] {len(entries)} entries")
    return entries


# ─── 2. GLM-5 筛选 7 个话题 ───────────────────────────────
TOPIC_SELECT_PROMPT = """你是 AskDrLiu.com（肝胆外科医生刘波主任的科普网站）的内容策划。

以下是本周抓取的医学资讯和患者热点讨论（共{total}条），请从中挑选**最适合科普写作的7个话题**。

选题标准（严格）：
1. 仅限肝脏及胆囊健康，优先以下方向：保胆、胆囊炎、胆囊结石、胆囊切除术后营养、胆囊与健康长寿关联
2. 与上述方向无关的内容（泛营养、泛养生、非肝胆系统）一律剔除
3. 有医学文献支撑或患者真实痛点
4. 话题多样，不重复同一主题

输入数据（JSON 数组）：
{entries_json}

输出格式（JSON 数组，7个元素）：
[
  {{
    "rank": 1,
    "title_zh": "中文选题标题（20字以内）",
    "reason": "选题理由（一句话）",
    "source_title": "原始标题",
    "source_url": "来源URL",
    "source_type": "pubmed|reddit|news",
    "category": "保胆|胆囊炎|胆囊结石|胆囊切除术后营养|胆囊与长寿|肝脏健康"
  }},
  ...
]
只输出 JSON，不要其他内容。"""


def _call_glm(messages, temperature=0.3):
    client = ZhipuAI(api_key=ZHIPU_KEY)
    # 优先 glm-5，失败回退 glm-4-plus
    for model in [GLM_MODEL, GLM_FALLBACK]:
        try:
            resp = client.chat.completions.create(
                model=model,
                temperature=temperature,
                messages=messages,
            )
            return resp.choices[0].message.content.strip(), model
        except Exception as ex:
            print(f"[WARN] model {model} failed: {ex}")
            continue
    raise RuntimeError("All GLM models failed")


def _extract_json_array(text: str):
    clean = re.sub(r"```json\s*|\s*```", "", text).strip()
    try:
        return json.loads(clean)
    except Exception:
        m = re.search(r"\[[\s\S]*\]", clean)
        if not m:
            raise
        return json.loads(m.group(0))


def select_topics(all_entries):
    if not ZHIPU_KEY:
        raise RuntimeError("Missing ZHIPU_API_KEY")

    sample = random.sample(all_entries, min(50, len(all_entries)))
    entries_json = json.dumps(
        [{"title": e["title"], "url": e["link"], "summary": e["summary"][:200], "source": e["source"]}
         for e in sample],
        ensure_ascii=False
    )

    text, model_used = _call_glm(
        [{"role": "user", "content": TOPIC_SELECT_PROMPT.format(total=len(sample), entries_json=entries_json)}],
        temperature=0.3,
    )
    topics = _extract_json_array(text)
    print(f"[Topics] Selected {len(topics)} topics by {model_used}")
    return topics[:10]


# ─── 3. 生成单篇草稿 ─────────────────────────────────────
ARTICLE_SYSTEM = """你是 AskDrLiu.com 医学团队的科普撰稿人。
写作规则：
- 选题边界严格限定在肝脏/胆囊健康（保胆、胆囊炎、胆囊结石、胆囊切除术后营养、胆囊与长寿关联）
- 基于提供来源，不捏造研究结论
- 每篇聚焦1个核心搜索意图，标题与首段必须围绕该意图
- 字数1200-1800中文
- 结构：引子(H1后首段含核心关键词) → 机制/背景(H2) → 研究证据(H2) → 实用建议(3-5条，H2) → 就医指征(H2) → 常见问题FAQ(2-3问，H2) → 参考文献 → 免责声明
- 正文中至少包含2-3个站内相对链接（如 /blog /clinic /assessment）
- 文末必须包含：
  ⚠️ 免责声明：本文仅供医学科普参考，不构成个人诊疗建议。如您有相关症状或疑虑，请及时就诊于正规医疗机构，遵从医生的专业指导。
只输出 Markdown 正文，不要JSON，不要代码块。"""

ARTICLE_USER = """话题：{title_zh}
来源标题：{source_title}
来源链接：{source_url}
分类：{category}

请写一篇可直接发布的中文医学博客文章。"""

CATEGORY_EN_MAP = {
    "保胆": "Gallbladder Preservation",
    "胆囊炎": "Cholecystitis",
    "胆囊结石": "Gallstones",
    "胆囊切除术后营养": "Post-Cholecystectomy Nutrition",
    "胆囊与长寿": "Gallbladder & Longevity",
    "肝脏健康": "Liver Health",
}


def generate_article(topic):
    markdown, model_used = _call_glm(
        [
            {"role": "system", "content": ARTICLE_SYSTEM},
            {"role": "user", "content": ARTICLE_USER.format(**topic)},
        ],
        temperature=0.4,
    )
    markdown = markdown.strip()
    markdown = re.sub(r"^```markdown\s*|\s*```$", "", markdown).strip()

    title = topic["title_zh"].strip()[:40]
    plain = re.sub(r"[#>*`\-\[\]\(\)]", "", markdown)
    plain = re.sub(r"\s+", " ", plain).strip()
    excerpt = plain[:110]

    return {
        "title": title,
        "titleEn": title,
        "excerpt": excerpt,
        "excerptEn": excerpt[:150],
        "category": topic.get("category", "胆囊结石"),
        "categoryEn": CATEGORY_EN_MAP.get(topic.get("category", "胆囊结石"), "Gallstones"),
        "markdown": markdown,
        "model_used": model_used,
    }


# ─── 4. 生成 AIGC 配图 ──────────────────────────────────
def detect_unwanted_text(img_path: Path) -> bool:
    if not Image or not pytesseract:
        return False
    if not shutil.which("tesseract"):
        return False
    try:
        img = Image.open(img_path).convert("RGB")
        w, h = img.size
        rois = [img, img.crop((0, int(h * 0.72), w, h))]
        merged = "\n".join(
            pytesseract.image_to_string(roi, lang="chi_sim+eng") for roi in rois
        )
        merged_upper = merged.upper()
        if any(k in merged_upper for k in WATERMARK_HINTS):
            return True
        if TEXT_PATTERN.search(merged):
            return True
        return False
    except Exception:
        return False


def generate_image(category, slug):
    fallback = {
        "保胆": "/images/pocs-surgery.jpg",
        "胆囊炎": "/images/gallstone-prevention.jpg",
        "胆囊结石": "/images/gallstone-prevention.jpg",
        "胆囊切除术后营养": "/images/recovery-guide.jpg",
        "胆囊与长寿": "/images/dietary-guidance.jpg",
        "肝脏健康": "/images/liver-health.jpg",
    }
    if not SILICONFLOW_KEY:
        return fallback.get(category, "/images/pocs-surgery.jpg")

    prompt = IMAGE_PROMPTS.get(category, IMAGE_PROMPTS["default"]) + "。严格要求：no text, no letters, no characters, no words, no logo, no watermark, no signature."

    for model_name in SILICONFLOW_MODELS:
        for attempt in range(1, 3):
            try:
                payload = {
                    "model": model_name,
                    "prompt": prompt,
                    "image_size": "1280x720",
                }
                resp = requests.post(
                    SILICONFLOW_URL,
                    headers={
                        "Authorization": f"Bearer {SILICONFLOW_KEY}",
                        "Content-Type": "application/json",
                    },
                    json=payload,
                    timeout=120,
                )
                resp.raise_for_status()
                data = resp.json().get("data", [])
                if not data:
                    raise RuntimeError("No image data from SiliconFlow")

                if data[0].get("url"):
                    img_data = requests.get(data[0]["url"], timeout=60).content
                elif data[0].get("b64_json"):
                    import base64
                    img_data = base64.b64decode(data[0]["b64_json"])
                else:
                    raise RuntimeError("No image URL/base64 from SiliconFlow")

                fname = f"blog-{slug[:40]}.jpg"
                img_path = IMAGES_DIR / fname
                img_path.write_bytes(img_data)

                if detect_unwanted_text(img_path):
                    print(f"  [WARN] text/watermark detected ({model_name}, attempt {attempt}), retrying...")
                    try:
                        img_path.unlink(missing_ok=True)
                    except Exception:
                        pass
                    continue

                print(f"  [IMG] {fname} via {model_name}")
                return f"/images/blog/{fname}"
            except Exception as ex:
                print(f"  [WARN] Image failed ({model_name}, attempt {attempt}): {ex}")
                continue

    return fallback.get(category, "/images/pocs-surgery.jpg")


# ─── 5. 保存草稿 ─────────────────────────────────────────
def make_slug(title):
    clean = re.sub(r"[^\w\s-]", "", title, flags=re.UNICODE)
    clean = re.sub(r"\s+", "-", clean.strip()).lower().strip("-")[:60]
    if not clean:
        clean = "post"
    # 去掉随机后缀，改为可读 slug；若重复再加短哈希
    base = clean
    path = DRAFTS_DIR / f"{base}.md"
    if path.exists():
        tail = hashlib.md5(title.encode("utf-8")).hexdigest()[:6]
        base = f"{base}-{tail}"
    return base


def build_seo_fields(data: dict):
    title = (data.get("title") or "").strip()
    excerpt = re.sub(r"\s+", " ", (data.get("excerpt") or "").strip())
    seo_title = title[:38] if len(title) > 38 else title
    seo_desc = excerpt[:145] if len(excerpt) > 145 else excerpt
    return seo_title, seo_desc


def save_draft(slug, data, image_url, source_url, publish_date):
    seo_title, seo_desc = build_seo_fields(data)
    header = f"""---
title: {data['title']}
titleEn: {data['titleEn']}
excerpt: {data['excerpt']}
excerptEn: {data['excerptEn']}
seoTitle: {seo_title}
seoDescription: {seo_desc}
date: {publish_date}
category: {data['category']}
categoryEn: {data['categoryEn']}
imageUrl: {image_url}
author: AskDrLiu.com
source: {source_url}
status: draft
---

"""
    path = DRAFTS_DIR / f"{slug}.md"
    path.write_text(header + data["markdown"].strip() + "\n", encoding="utf-8")
    return str(path)


# ─── 6. 写入发布队列 ─────────────────────────────────────
def write_queue(queue_entries):
    QUEUE_FILE.write_text(
        json.dumps({"updated": datetime.now().strftime("%Y-%m-%d"), "posts": queue_entries},
                   ensure_ascii=False, indent=2),
        encoding="utf-8"
    )
    print(f"[Queue] Written {len(queue_entries)} entries to {QUEUE_FILE}")


# ─── 7. Telegram 通知 ─────────────────────────────────────
def send_telegram(topics, queue_entries):
    if not TG_TOKEN:
        print("[WARN] No TELEGRAM_BOT_TOKEN, skipping notification")
        return
    lines = ["📚 本周博客话题（草稿已生成）\n"]
    for i, (t, q) in enumerate(zip(topics[:len(queue_entries)], queue_entries), 1):
        lines.append(f"{i}. {t['title_zh']} [{t['category']}]")
        lines.append(f"   计划发布：{q['publish_date']}")
    lines.append("\n✅ 默认按序自动发布")
    lines.append("如需调整，请在24小时内回复序号+指令")
    text = "\n".join(lines)
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{TG_TOKEN}/sendMessage",
            json={"chat_id": TG_CHAT_ID, "text": text},
            timeout=15
        )
        print(f"[TG] Sent: {resp.status_code}")
    except Exception as ex:
        print(f"[WARN] Telegram failed: {ex}")


# ─── Main ─────────────────────────────────────────────────
def main():
    print("=== Weekly Pipeline Start ===")
    print(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")

    # 1. 抓取话题
    rss_entries    = fetch_rss_entries()
    reddit_entries = fetch_reddit_entries()
    all_entries    = rss_entries + reddit_entries
    print(f"Total entries: {len(all_entries)}\n")

    # 2. GLM 筛选 7 个话题
    topics = select_topics(all_entries)

    # 3. 生成草稿 + 配图
    queue_entries = []
    # 发布日期：从下周一开始，每天一篇
    next_monday = datetime.now() + timedelta(days=(7 - datetime.now().weekday()))
    
    for i, topic in enumerate(topics):
        publish_date = (next_monday + timedelta(days=i)).strftime("%Y-%m-%d")
        print(f"\n[{i+1}/7] {topic['title_zh']} → {publish_date}")
        
        try:
            # 生成文章
            data = generate_article(topic)
            slug = make_slug(topic["title_zh"])
            
            # 生成配图
            image_url = generate_image(topic["category"], slug)
            
            # 保存草稿
            path = save_draft(slug, data, image_url, topic["source_url"], publish_date)
            print(f"  [Draft] {path}")
            
            seo_title, seo_desc = build_seo_fields(data)
            queue_entries.append({
                "publish_date": publish_date,
                "slug": slug,
                "title": data["title"],
                "category": data["category"],
                "imageUrl": image_url,
                "excerpt": data["excerpt"],
                "excerptEn": data["excerptEn"],
                "titleEn": data["titleEn"],
                "categoryEn": data["categoryEn"],
                "seoTitle": seo_title,
                "seoDescription": seo_desc,
                "status": "draft"
            })
        except Exception as ex:
            print(f"  [ERROR] {ex}")
            continue

    # 4. 写队列
    write_queue(queue_entries)

    # 5. Telegram 通知
    send_telegram(topics, queue_entries)

    print(f"\n=== Done: {len(queue_entries)}/7 drafts generated ===")


if __name__ == "__main__":
    main()
